"""Initial migration via exec

Revision ID: 02fd3cabb547
Revises: 'None'
Create Date: 2025-04-03 03:57:17.768809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fd3cabb547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create 'users' table first
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create 'worlds' table second
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_id'), 'worlds', ['id'], unique=False)
    op.create_index(op.f('ix_worlds_name'), 'worlds', ['name'], unique=False)

    # --- The rest of the tables ---
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_world_id'), 'campaigns', ['world_id'], unique=False)
    op.create_table('character_tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_tag_types_id'), 'character_tag_types', ['id'], unique=False)
    op.create_index(op.f('ix_character_tag_types_world_id'), 'character_tag_types', ['world_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index(op.f('ix_characters_world_id'), 'characters', ['world_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_world_id'), 'events', ['world_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('WORLD', 'CHARACTER', 'ITEM', 'LOCATION', 'ORGANIZATION', 'EVENT', 'CAMPAIGN', 'SESSION', name='targettypeenum'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_target_id'), 'images', ['target_id'], unique=False)
    op.create_index(op.f('ix_images_target_type'), 'images', ['target_type'], unique=False)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_index(op.f('ix_images_world_id'), 'images', ['world_id'], unique=False)
    op.create_table('item_tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tag_types_id'), 'item_tag_types', ['id'], unique=False)
    op.create_index(op.f('ix_item_tag_types_world_id'), 'item_tag_types', ['world_id'], unique=False)
    op.create_table('location_tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_tag_types_id'), 'location_tag_types', ['id'], unique=False)
    op.create_index(op.f('ix_location_tag_types_world_id'), 'location_tag_types', ['world_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_parent_location_id'), 'locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('ix_locations_world_id'), 'locations', ['world_id'], unique=False)
    op.create_table('organization_tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_tag_types_id'), 'organization_tag_types', ['id'], unique=False)
    op.create_index(op.f('ix_organization_tag_types_world_id'), 'organization_tag_types', ['world_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('parent_organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_parent_organization_id'), 'organizations', ['parent_organization_id'], unique=False)
    op.create_index(op.f('ix_organizations_world_id'), 'organizations', ['world_id'], unique=False)
    op.create_table('world_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_invites_id'), 'world_invites', ['id'], unique=False)
    op.create_index(op.f('ix_world_invites_token'), 'world_invites', ['token'], unique=True)
    op.create_index(op.f('ix_world_invites_world_id'), 'world_invites', ['world_id'], unique=False)
    op.create_table('world_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_users_id'), 'world_users', ['id'], unique=False)
    op.create_index(op.f('ix_world_users_user_id'), 'world_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_world_users_world_id'), 'world_users', ['world_id'], unique=False)
    op.create_table('campaign_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_invites_campaign_id'), 'campaign_invites', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_invites_id'), 'campaign_invites', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_invites_token'), 'campaign_invites', ['token'], unique=True)
    op.create_table('character_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_organizations_character_id'), 'character_organizations', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_organizations_id'), 'character_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_character_organizations_organization_id'), 'character_organizations', ['organization_id'], unique=False)
    op.create_table('character_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_tag_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_tag_type_id'], ['character_tag_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_tags_character_id'), 'character_tags', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_tags_character_tag_type_id'), 'character_tags', ['character_tag_type_id'], unique=False)
    op.create_index(op.f('ix_character_tags_id'), 'character_tags', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_character_id'), 'items', ['character_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_location_id'), 'items', ['location_id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_index(op.f('ix_journals_character_id'), 'journals', ['character_id'], unique=True)
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.create_table('location_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_tag_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_tag_type_id'], ['location_tag_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_tags_id'), 'location_tags', ['id'], unique=False)
    op.create_index(op.f('ix_location_tags_location_id'), 'location_tags', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_tags_location_tag_type_id'), 'location_tags', ['location_tag_type_id'], unique=False)
    op.create_table('organization_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('organization_tag_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_tag_type_id'], ['organization_tag_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_tags_id'), 'organization_tags', ['id'], unique=False)
    op.create_index(op.f('ix_organization_tags_organization_id'), 'organization_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_tags_organization_tag_type_id'), 'organization_tags', ['organization_tag_type_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_campaign_id'), 'sessions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_sessions_date_time'), 'sessions', ['date_time'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('user_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('GM', 'PLAYER', 'SPECTATOR', name='campaignroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_campaigns_campaign_id'), 'user_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_user_campaigns_id'), 'user_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_user_campaigns_user_id'), 'user_campaigns', ['user_id'], unique=False)
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilities_id'), 'availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_availabilities_session_id'), 'availabilities', ['session_id'], unique=False)
    op.create_index(op.f('ix_availabilities_user_id'), 'availabilities', ['user_id'], unique=False)
    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_tag_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_tag_type_id'], ['item_tag_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tags_id'), 'item_tags', ['id'], unique=False)
    op.create_index(op.f('ix_item_tags_item_id'), 'item_tags', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_tags_item_tag_type_id'), 'item_tags', ['item_tag_type_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_journal_id'), 'journal_entries', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_session_id'), 'journal_entries', ['session_id'], unique=False)
    op.create_table('session_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_characters_character_id'), 'session_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_session_characters_id'), 'session_characters', ['id'], unique=False)
    op.create_index(op.f('ix_session_characters_session_id'), 'session_characters', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_characters_session_id'), table_name='session_characters')
    op.drop_index(op.f('ix_session_characters_id'), table_name='session_characters')
    op.drop_index(op.f('ix_session_characters_character_id'), table_name='session_characters')
    op.drop_table('session_characters')
    op.drop_index(op.f('ix_journal_entries_session_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_journal_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_item_tags_item_tag_type_id'), table_name='item_tags')
    op.drop_index(op.f('ix_item_tags_item_id'), table_name='item_tags')
    op.drop_index(op.f('ix_item_tags_id'), table_name='item_tags')
    op.drop_table('item_tags')
    op.drop_index(op.f('ix_availabilities_user_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_session_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_id'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_user_campaigns_user_id'), table_name='user_campaigns')
    op.drop_index(op.f('ix_user_campaigns_id'), table_name='user_campaigns')
    op.drop_index(op.f('ix_user_campaigns_campaign_id'), table_name='user_campaigns')
    op.drop_table('user_campaigns')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_date_time'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_campaign_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_organization_tags_organization_tag_type_id'), table_name='organization_tags')
    op.drop_index(op.f('ix_organization_tags_organization_id'), table_name='organization_tags')
    op.drop_index(op.f('ix_organization_tags_id'), table_name='organization_tags')
    op.drop_table('organization_tags')
    op.drop_index(op.f('ix_location_tags_location_tag_type_id'), table_name='location_tags')
    op.drop_index(op.f('ix_location_tags_location_id'), table_name='location_tags')
    op.drop_index(op.f('ix_location_tags_id'), table_name='location_tags')
    op.drop_table('location_tags')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_character_id'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_items_location_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_character_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_character_tags_id'), table_name='character_tags')
    op.drop_index(op.f('ix_character_tags_character_tag_type_id'), table_name='character_tags')
    op.drop_index(op.f('ix_character_tags_character_id'), table_name='character_tags')
    op.drop_table('character_tags')
    op.drop_index(op.f('ix_character_organizations_organization_id'), table_name='character_organizations')
    op.drop_index(op.f('ix_character_organizations_id'), table_name='character_organizations')
    op.drop_index(op.f('ix_character_organizations_character_id'), table_name='character_organizations')
    op.drop_table('character_organizations')
    op.drop_index(op.f('ix_campaign_invites_token'), table_name='campaign_invites')
    op.drop_index(op.f('ix_campaign_invites_id'), table_name='campaign_invites')
    op.drop_index(op.f('ix_campaign_invites_campaign_id'), table_name='campaign_invites')
    op.drop_table('campaign_invites')
    op.drop_index(op.f('ix_world_users_world_id'), table_name='world_users')
    op.drop_index(op.f('ix_world_users_user_id'), table_name='world_users')
    op.drop_index(op.f('ix_world_users_id'), table_name='world_users')
    op.drop_table('world_users')
    op.drop_index(op.f('ix_world_invites_world_id'), table_name='world_invites')
    op.drop_index(op.f('ix_world_invites_token'), table_name='world_invites')
    op.drop_index(op.f('ix_world_invites_id'), table_name='world_invites')
    op.drop_table('world_invites')
    op.drop_index(op.f('ix_organizations_world_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_organization_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_tag_types_world_id'), table_name='organization_tag_types')
    op.drop_index(op.f('ix_organization_tag_types_id'), table_name='organization_tag_types')
    op.drop_table('organization_tag_types')
    op.drop_index(op.f('ix_locations_world_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_parent_location_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_location_tag_types_world_id'), table_name='location_tag_types')
    op.drop_index(op.f('ix_location_tag_types_id'), table_name='location_tag_types')
    op.drop_table('location_tag_types')
    op.drop_index(op.f('ix_item_tag_types_world_id'), table_name='item_tag_types')
    op.drop_index(op.f('ix_item_tag_types_id'), table_name='item_tag_types')
    op.drop_table('item_tag_types')
    op.drop_index(op.f('ix_images_world_id'), table_name='images')
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_target_type'), table_name='images')
    op.drop_index(op.f('ix_images_target_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_events_world_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_characters_world_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_tag_types_world_id'), table_name='character_tag_types')
    op.drop_index(op.f('ix_character_tag_types_id'), table_name='character_tag_types')
    op.drop_table('character_tag_types')
    op.drop_index(op.f('ix_campaigns_world_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')

    # Drop worlds and users last
    op.drop_index(op.f('ix_worlds_name'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 