name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Build and Push to GitHub Container Registry
        run: |
          docker build -t ghcr.io/blbin/sesplan-backend:latest ./backend
          docker push ghcr.io/blbin/sesplan-backend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/sesplan
            docker pull ghcr.io/novakpetr/sesplan-backend:latest
            docker compose up -d --remove-orphans
            docker image prune -af
