name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Přihlášení do GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u blbin --password-stdin

      - name: Build and Push to GitHub Container Registry
        run: |
          docker build -t ghcr.io/blbin/sesplan-backend:latest ./backend
          docker push ghcr.io/blbin/sesplan-backend:latest

