name: Update Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "docker-compose.yml"  # Sledujeme jen změny v tomto souboruss

jobs:
  update-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload updated docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/srv/sesplan/"

      - name: Deploy new stack with zero-downtime
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/sesplan
            docker compose pull
            docker compose up -d 
            docker image prune -af

